### ISSUE TITLE
"option" and "left-right arrow" key pairs does not work [API-1562]

### ISSUE THREAD

**Issue by feysahin** [hazelcast/hazelcast-commandline-client#112]
When the user wants to scroll through words in the commandline with option+arrow, commanline does not allow this.

**Reproducer:**
(computer-> macOS version: 11.6.7)
To change the address by going to the beginning of the address in terminal, this case happened:
I entered this command: `hzc localhost:5701@dev> sql -a 127.0.0.1:5701`
Secondly, after used "option + left-arrow" key pair (3 times) and "option +  right-arrow" key pair (1 time), I get this on my terminal:
`hhzhzchzc localhost:5701@dev> sql -a 127.0.0.1:5701?f?f?f?b`

**Comment by utku-caglayan** [comment]
fixed with https://github.com/hazelcast/hazelcast-commandline-client/pull/142
