### ISSUE TITLE
Previous SQL queries remain in the prompt

### ISSUE THREAD

**Issue by JakeSCahill** [hazelcast/hazelcast-commandline-client#138]
When using the SQL prompt (`hzc sql`), the previous query remains even after you execute it with ^E. As a user, you need to manually delete the previous command before entering another one, otherwise you get an error because you cannot execute two queries at once.

**Comment by mehmettokgoz** [comment]
You can erase the previous query with ^U. I am not sure whether we should directly erase it or not since the user might want to write it incrementally and see the results.

**Comment by yuce** [comment]
This issue is currently N/A, so closing.
