### ISSUE TITLE
Enhancements for Management Center [API-1899]

### ISSUE THREAD

**Issue by nilnullneil** [hazelcast/hazelcast-commandline-client#185]
Be able to set `instanceName` and `labels` for CLC

**Comment by yuce** [comment]
Fixed by: https://github.com/hazelcast/hazelcast-commandline-client/pull/194 The user can use `CLC_CLIENT_NAME` to override the default client name which is `USER@HOST` and `CLC_CLIENT_LABELS` with comma separated list of labels to override the default `CLC`, `User:USER@HOST` labels.
