### ISSUE TITLE
Hazelcast Command-Line Client (CLC) - map load exception

### ISSUE THREAD

**Issue by Puneet1726** [hazelcast/hazelcast-commandline-client#363]
Hi Team,

We are loading a map using hazelcast clc and getting below exception.

_com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:102): Map XXXXXX is still loading data from external store._

clc -c config.yaml map get -n name --key-type string --timeout 20m.

We have a map which contains around 20GB of data. It is loading the map in  the backend but we have a requirement to load multiple maps sequentially.

I have tried to add timeout but no luck.
Please let me know how to proceed on this.

**Comment by yuce** [comment]
Hi @Puneet1726 I'm closing this ticket since the support team is handling this issue, but please feel free to re-open it if necessary.
