### ISSUE TITLE
DMT: Migration report is printed on single line [CLC-420]

### ISSUE THREAD

**Issue by sumnerib** [hazelcast/hazelcast-commandline-client#415]
The report generated after a migration has either completed or failed is written on a single line in the resulting text file. The "\n\n" characters are printed literally in the file.

Example:

```
"Report for migration id=286ab45e-e0d7-4a5a-b5be-4df743c9bbc1\n\nStarted time: 2023-10-23T18:59:06.887555Z\n\nStatus: Completed\nCompleted time: 2023-10-23T14:59:07.730024-04:00\n\nThe migration of the following data structures was completed:\n\nIMap:\n- my-map2 (100 entries total) time 0h 0m 0s\n\nThe migration of the following data structures was canceled:\n\nThe migration of the following data structures was failed:\n\nThe migration of the following data structures was not started:\n\n"
```

This can be reproduced by following the instructions in the README included in the DMT package. These steps are:

1. `docker run -p 127.0.0.1:5701:5701 -e HZ_CLUSTERNAME=source hazelcast/hazelcast:4.2.7`
2. `for i in {1..1000}; do clc -c source.yaml map --name my-map set key-$i value-$i --quiet; done && echo OK`
3. `docker run -e HZ_NETWORK_PORT_PORT=5901 -p 127.0.0.1:5901:5901 -e HZ_LICENSEKEY="yourlicensekey" -e HZ_CLUSTERNAME=target hazelcast/hazelcast-enterprise:5.3.2-SNAPSHOT-slim`
4. `HZ_NETWORK_PORT_PORT=5702 HZ_CLUSTERNAME=migration ./bin/hz start`
5. `./bin/dmt_[platform]_[arch] --config migration.yaml start migration_config --yes`

Check the generated `migration_report_*.txt` file.

**Comment by kutluhanmetin** [comment]
fixed with: https://github.com/hazelcast/hazelcast-commandline-client/pull/419
