### ISSUE TITLE
DMT: dmt command hangs when unable to connect w/ the migration cluster [CLC-431]

### ISSUE THREAD

**Issue by sumnerib** [hazelcast/hazelcast-commandline-client#426]
If given a bad config for the migration cluster or if the migration cluster is unavailable, the `dmt` command will hang indefinitely. 

To reproduce: Without starting any cluster, simply run the following command (where `migration.yaml` is a valid clc client config): `./bin/dmt --config migration.yaml start migration_config --yes`

**Comment by sumnerib** [comment]
Spins on the `estimate` command when unable to connect to the migration cluster as well: 
```
bin/dmt estimate --config migration.yaml migration_config       

Hazelcast Data Migration Tool v5.3.0
(c) 2023 Hazelcast, Inc.


Estimation usually ends within 15 seconds.
       [1/2] Connecting to the migration cluster (Ctrl+C to cancel)    
```

**Comment by yuce** [comment]
Fixed by: https://github.com/hazelcast/hazelcast-commandline-client/pull/429
