### ISSUE TITLE
ReplicatedMap Support

### ISSUE THREAD

**Issue by yuce** [hazelcast/hazelcast-commandline-client#51]
Implement support for `ReplicatedMap`. 

If you would like the feature to be implemented, please add a :+1: to this issue. If you have specific needs regarding `ReplicatedMap`, feel free to drop a comment with more details.

Your feedback will drive the priority for implementation!

**Comment by donatelloOo** [comment]
So there is no support for replicated map, right ? Or is it only through some .star script ?

**Comment by yuce** [comment]
Hi @donatelloOo,

There's no replicated map support at the moment, and there is no support for it via scripting.
It would be great to know more about your use case though.
Would you be open to talk about it?
You can join our community Slack is at: https://slack.hazelcast.com/
