### ISSUE TITLE
Usage for missing value flag is absent

### ISSUE THREAD

**Issue by nevzatseferoglu** [hazelcast/hazelcast-commandline-client#54]
There isn't usage recommendation for the missing value.
```bash
> hzc map put --name my-map --key my-key
Error: One of the value flag must be set
```

**Comment by yuce** [comment]
When the `--value` flag is left out, CLC shouldn't try to connect to the cluster. And it also should print the usage information like the missing `--key`.

**Comment by yuce** [comment]
This is not applicable anymore, closing the ticket.
