### ISSUE TITLE
Help message is inconsistent

### ISSUE THREAD

**Issue by utku-caglayan** [hazelcast/hazelcast-commandline-client#57]
![sn__mek_z_2022-02-14_15-57-41](https://user-images.githubusercontent.com/8045232/154015525-0dfe9c41-8207-408b-b619-ac6626dc55a7.png)
We should be consistent with these messages. For example:
- In "Available Commands" section, some explanations start with an uppercase where most not. (Prefer all first letters to be uppercase)
- In "Flags" section, some sentences and with a period and some don't. (Prefer no period)
- replicatedmap is not easy to read in help text. Let's change it to ReplicatedMap. Similarly we should change for Multimap too.

Also this image is only for help command. We should check other commands for this as well. (map get help for example)

**Comment by yuce** [comment]
This is not applicable anymore, closing the ticket.
