### ISSUE TITLE
Verbose flag + interactive mode ends up with bad terminal experience

### ISSUE THREAD

**Issue by nevzatseferoglu** [hazelcast/hazelcast-commandline-client#63]
Verbose mode can ends up with missleading output with certain arguments in interactive mode.

For example,
`./hazelcast-commandline-client --cluster-name=dev --verbose`
It connects to cluster while printing logs to the standard output and also opens interactive mode. When cluster state change in denoted log level on cluster, logs are printed to the same shell session by racing with interactive mode. They overlaps with each other.
<img width="817" alt="Screen Shot 2022-04-28 at 14 21 18" src="https://user-images.githubusercontent.com/43863606/165743204-64955f7a-bbb0-4330-9d09-5c4557d12913.png">

Disabling verbose output for interactive mode can be a solution ?

**Comment by Holmistr** [comment]
:+1:

**Comment by yuce** [comment]
This is not applicable anymore, closing the ticket.
