### ISSUE TITLE
Paste functionality does not work

### ISSUE THREAD

**Issue by utku-caglayan** [hazelcast/hazelcast-commandline-client#70]
On ubuntu 22.04 when I copy a multiline SQL string into the browser it does not show it properly:

To reproduce

`hzc sql`

and paste the following to the query textbox:
```
CREATE MAPPING my_map
TYPE IMap
OPTIONS (
    'keyFormat'='int',
    'valueFormat'='varchar'
)
```
If you start deleting some characters, you will notice that only the last line is shown in the textbox.

Another note: in [terminator](https://terminator-gtk3.readthedocs.io/en/latest/) only the last line is shown. However, in ubuntu 22.04's builtin terminal application, it is worse: two lines are shown on top of each other somehow:
![168760665-7712b03c-9768-4fb1-aebf-25457dc6b174](https://user-images.githubusercontent.com/8045232/169026370-9a67062d-942d-4ed0-8306-d543e75b3d03.png)
![168760751-8dd70e9f-2316-4cd9-b593-267e9c2dd26d](https://user-images.githubusercontent.com/8045232/169026451-a7ee6674-d729-4a20-891f-885135035434.png)

**Comment by yuce** [comment]
This is not applicable anymore, closing the ticket.
