### ISSUE TITLE
Cannot terminate the process

### ISSUE THREAD

**Issue by JakeSCahill** [hazelcast/hazelcast-commandline-client#85]
1. Start a local member on localhost:5701
2. Execute `hzc sql -a 127.0.0.1:5702` to try to connect to a non-existent member.

The logs are flooded with error messages and Ctrl + C does not work to terminate the process. I had to force close the Terminal window.

**Comment by jerrinot** [comment]
+1, I just stumbled upon it too, it's annoying.
