### ISSUE TITLE
Can't disable/switch from Interactive mode [API-1477]

### ISSUE THREAD

**Issue by angelasimms** [hazelcast/hazelcast-commandline-client#96]
Hi,

I'm running Ubuntu on Windows. 

I can enable interactive mode from the bash: `hzc #` but I can't disable it. I've tried CTRL + C, exit, complete shutdown, renaming my bash profile... I've also tried switching to SQL mode.

**Comment by yuce** [comment]
Tracking this at: https://hazelcast.atlassian.net/browse/API-1455

**Comment by utku-caglayan** [comment]
@angelasimms thanks for reporting. We are not exaclty sure what is the scenario but hopefully #132 fixed the issue. Please feel free to re-open if you experience it again.
